redis:
  image: redis
web:
  build: .
  command: foreman start
  ports:
    - "9292:9292"
  volumes:
    - .:/opt/empregoligado
  links:
    - redis
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
    - PROJECT_NAME=production
  stdin_open: true
  tty: true
