web:
  build: .
  command: foreman start
  ports:
    - "9292:9292"
  volumes:
    - .:/opt/empregoligado
  links:
    - redis
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
redis:
  image: redis