default: &default
  redis:
    url: "redis://127.0.0.1:6379/0"
  jobs_api:
    url: 'http://localhost:9292'

development_docker:
  <<: *default
  redis:
    url: "redis://redis:6379/0"

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
